item_list = ['bread','milk','egg','butter','cocaa']
student_marks = [78,47,96,55,34]
hetero_list = [1,2,3,]

In [23]:
student_marks = [78,47,96,55,34]
for i in range(len(student_marks)):
    student_marks[i]+=5
print(student_marks)


[83, 52, 101, 60, 39]


In [24]:
import numpy as np
cars = np.array(['chevrolet chevelle malivu','buick skylark 320','playmouth satellite','amc rebel sst','frod torino'])
cars[1]

'buick skylark 320'

In [25]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print("median horsepower = ",np.median(horsepower_arr))

median horsepower =  150.0


In [26]:
horsepower = [130,165,140,130,110]
horsepower_arr = np.array(horsepower)
print("median horsepower = ",np.median(horsepower_arr))

median horsepower =  130.0


In [27]:
student_marks=([67,45],[90,92],[66,72],[32,40])
student_marks_arr=np.array(student_marks)
student_marks_arr+=(5,10)
print(student_marks_arr)


[[ 72  55]
 [ 95 102]
 [ 71  82]
 [ 37  50]]


In [28]:
arr = np.linspace(0,10)
print(arr)
print('length of arr:',len(arr))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
length of arr: 50


In [29]:
np.arange(0,10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [30]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [72]:
horsepower = [130, 165, 150, 150,140]
horsepower_arr = np.array(horsepower)
print('original array: ', (horsepower_arr)
print('Sorted array: ', np.sort(horsepower_arr)
print('original array after sorting: ',(horsepower_arr)


SyntaxError: invalid syntax. Perhaps you forgot a comma? (3592501906.py, line 3)

In [ ]:
horsepower = [130, 165, 150, 150,140]
horsepower_arr = np.array(horsepower)
print('original array: ', horsepower_arr)
print('original array after sorting: ', horsepower_arr)


In [ ]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
filter_arr = horsepower_arr > 135
newarr = horsepower_arr[filter_arr]
print(filter_arr)
print(newarr)

In [ ]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
x = np.where(horsepower_arr >= 150)
print(x)
horsepower_arr[x]

In [ ]:
horsepower = [130, 165, 150, 150, 140]
horsepower_arr = np.array(horsepower)
print("maximum horsepower:",np.min(horsepower_arr))
print("minimum horsepower:",np.max(horsepower_arr))                          
    

In [ ]:
horsepower=[138,165,150,150,140]
horsepower_arr=np.array(horsepower)
print("mean horsepower=",np.mean(horsepower_arr))

In [41]:
horsepower=[155,168,211,505,113]
horsepower_arr=np.array(horsepower)
print("median horsepower=",np.median(horsepower_arr))

median horsepower= 168.0


In [40]:
cars=np.array(['chevrolet chevelle malibu','buick skylark 320','plymouth satellite','amc rebel sst','ford torino'])
cars[1:4]

array(['buick skylark 320', 'plymouth satellite', 'amc rebel sst'],
      dtype='<U25')

In [36]:
import numpy as np
step_walk=([[1,6012],[2,7079],[3,6886],[4,7230],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9569]])
step_walk=np.array(step_walk)
print(step_walk)

[[   1 6012]
 [   2 7079]
 [   3 6886]
 [   4 7230]
 [   5 4598]
 [   6 5564]
 [   7 6971]
 [   8 7763]
 [   9 8032]
 [  10 9569]]


In [35]:
day_num=[1,2,3,4,5,6,7,8,91,10]
step_walk=[6012,7079,6886,7230,4598,5564,6971,7763,8032,9569]
new_arr=np.array([day_num,step_walk])
print(new_arr)
print(day_num)
print(step_walk)

[[   1    2    3    4    5    6    7    8   91   10]
 [6012 7079 6886 7230 4598 5564 6971 7763 8032 9569]]
[1, 2, 3, 4, 5, 6, 7, 8, 91, 10]
[6012, 7079, 6886, 7230, 4598, 5564, 6971, 7763, 8032, 9569]


In [34]:
step_walk=([[1,6012],[2,7079],[3,6886],[4,7230],[5,4598],[6,5564],[7,6971],[8,7763],[9,8032],[10,9569]])
step_walk=np.array(step_walk)
step_walk+=(0,2000)
print(step_walk)



[[    1  8012]
 [    2  9079]
 [    3  8886]
 [    4  9230]
 [    5  6598]
 [    6  7564]
 [    7  8971]
 [    8  9763]
 [    9 10032]
 [   10 11569]]


In [42]:
arr=np.where(new_arr[:,]>9000)
print(arr)
print(new_arr[arr])

(array([1], dtype=int64), array([9], dtype=int64))
[9569]


In [57]:
import numpy as np
day_number=np.arange(1,11)
steps_walked=[6012,7079,6886,7230,4598,5564,6971,7763,8032,9569]
arr = np.array([day_number,steps_walked])
arr = arr.T
arr

array([[   1, 6012],
       [   2, 7079],
       [   3, 6886],
       [   4, 7230],
       [   5, 4598],
       [   6, 5564],
       [   7, 6971],
       [   8, 7763],
       [   9, 8032],
       [  10, 9569]])

In [58]:
matched=arr[:,1]>9000
matched
new_arr=arr[matched]
new_arr

array([[  10, 9569]])

In [59]:
sortedArr = arr[arr[:,1].argsort()]
print('sorted 2D numpy array')
print(sortedArr)

sorted 2D numpy array
[[   5 4598]
 [   6 5564]
 [   1 6012]
 [   3 6886]
 [   7 6971]
 [   2 7079]
 [   4 7230]
 [   8 7763]
 [   9 8032]
 [  10 9569]]


In [60]:
import numpy as np
arr = np.array([[1,2],[3,4]])
print(np.sum(arr))
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))


10
[4 6]
[3 7]


In [62]:
import numpy as np
arr=np.array([[1,2],[3,4]])
print(np.mean(arr))
print(np.mean(arr,axis=0))
print(np.mean(arr,axis=1))

2.5
[2. 3.]
[1.5 3.5]


In [69]:
import numpy as np
arr= np.array([[1,2],[3,4]])
print(np.max(arr))
print(np.max(arr,axis=0))
print(np.max(arr,axis=1))
      


      

4
[3 4]
[2 4]


In [70]:
import numpy as np
arr= np.array([[1,2],[3,4]])
print(np.min,(arr))
print(np.min(arr,axis=0))
print(np.min(arr,axis=1))


<function amin at 0x0000021F123C4400> [[1 2]
 [3 4]]
[1 2]
[1 3]


In [5]:
import numpy as np
arr = np.array([[1,2],[3,4]])
print(np.std(arr))
print(np.std(arr, axis=0))
print(np.std(arr, axis=1))


1.118033988749895
[1. 1.]
[0.5 0.5]


In [6]:
import numpy as np
arr = np.array([[1,2],[3,4]])
print(np.var(arr))
print(np.var(arr, axis=0))
print(np.var(arr, axis=1))

1.25
[1. 1.]
[0.25 0.25]


In [7]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result=arr1+arr2
print(result)

[5 7 9]


In [8]:
import numpy as np
arr1=np.array([4,5,6])
arr2=np.array([1,2,3])
result=arr1-arr2
print(result)

[3 3 3]


In [9]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result=arr1*arr2
print(result)

[ 4 10 18]


In [10]:
import numpy as np
arr1=np.array([4,6,8])
arr2=np.array([2,3,4])
result=arr1/arr2
print(result)

[2. 2. 2.]


In [12]:
import numpy as np
arr=np.array([2,3,4])
result=arr**2
print(result)

[ 4  9 16]


In [13]:
import numpy as np
arr=np.array([4,9,16])
result=np.sqrt(arr)
print(result)

[2. 3. 4.]


In [14]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([2,2,3])
result=arr1==arr2
print(result)

[False  True  True]


In [15]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
result_mean=np.mean(arr)
result_std=np.std(arr,axis=1)
result_sum=np.sum(arr,axis=0)
print(result_mean)
print(result_std)
print(result_sum)


3.5
[0.81649658 0.81649658]
[5 7 9]


In [16]:
import numpy as np
arr=np.array([2,3,4])
result=np.power(arr,2)
print(result)

[ 4  9 16]


In [19]:
import numpy as np
arr=np.array([1,5,10])
result=np.where(arr<5,arr,0)
print(result)

[1 0 0]


In [20]:
import numpy as np
arr=np.array([1,2,3,4,5,])
result=np.cumsum(arr)
print(result)

[ 1  3  6 10 15]


In [21]:
import numpy as np
arr=np.array([3,1,4,2,5])
result=np.sort(arr)
print(result)

[1 2 3 4 5]


In [23]:

S_X=np.array([[2,5,6,5],[4,8,6,5]])
S_Y=np.array([[6,7,5,9],[7,5,6,4]])
quaterly_difference=S_Y-S_X
print(quaterly_difference)


[[ 4  2 -1  4]
 [ 3 -3  0 -1]]


In [24]:
less_than_2=S_X<2
print(less_than_2)

[[False False False False]
 [False False False False]]


In [33]:
X_cumsum=np.cumsum(S_X,axis=1)
print(X_cumsum)
print(X_cumsum>=8)



[[ 2  7 13 18]
 [ 4 12 18 23]]
[[False False  True  True]
 [False  True  True  True]]


In [35]:
yearly_mean_X=np.mean(S_X,axis=1)
print(yearly_mean_X)

[4.5  5.75]


In [37]:
quaterly_mean_Y=np.mean(S_Y,axis=0)
print(quaterly_mean_Y)

[6.5 6.  5.5 6.5]


In [41]:
numbers=[1,2,3,4,5]
squared_numbers=map(lambda x:x**2, numbers)
print(list(squared_numbers))

[1, 4, 9, 16, 25]


In [43]:
numbers=[1,2,3,4,5]
even_numbers=filter(lambda x:x%2==0, numbers)
print(list(even_numbers))

[2, 4]


In [45]:
from functools import reduce 
numbers=[1,2,3,4,5]
sum_of_numbers=reduce(lambda x,y:x+y,numbers)
print (sum_of_numbers)

15


In [50]:
square=lambda x: x**2
print(square(5))

25
